# Generated by Django 5.0.6 on 2024-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='image_url',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(db_default=0),
        ),
    ]
