# Generated by Django 5.0.6 on 2024-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_productos_image_url_productos_price_productos_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
