# Generated by Django 5.0.6 on 2024-07-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_rename_productos_products_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
