# Generated by Django 5.0.6 on 2024-07-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_shoppingcart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user_id',
            new_name='user',
        ),
    ]
