# Generated by Django 5.0.6 on 2024-07-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_rename_user_id_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
